# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d4cfbbaba0af3f25fedbbcd26b74f45c64b31fa89d6911ea8fa921ba54edf0f9f9544e54be2543aa15e3221e84323ed35cb1528ce03d8a2af713adfd66d241b

test:
  secret_key_base: 4d66e83ef9019f45360e880e42e6dd842817d68d9f2c74548031db605e5d88c964089e9851d182ab5fa425f45a77bfa5d23a1326ed75698a391d064f99badaca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
